### PR TITLE
Some Updates

### PR DESCRIPTION
**Pull request by LukvonStrom**
MySQLi, using a config now, brought all content except of the config  to
one file

### CODE REVIEW

**Comment by J0ker98** [comment]
Do not remove the license please

**Comment by LukvonStrom** [comment]
?!? Line 2 - 18 in the index.php file is your license text and because i've forked your repo the original License file is included too ...

**Comment by J0ker98** [comment]
Seen it just now, perfect then ;)

If you want I have some ideas that we could implement for better security

**Comment by LukvonStrom** [comment]
I was thinking about some ways to avoid SQL Injections but I haven't implemented it because I thought that this is an admintool so a Injection protection would be useless

**Comment by LukvonStrom** [comment]
But avoiding Get was the biggest security enhancement I've made

**Comment by J0ker98** [comment]
An injection protection is never useless... I'll write something down and then contact you in about 3/4 hours ;)

**Comment by LukvonStrom** [comment]
Okay :)

**Pull request merged**
